import { Inter } from 'next/font/google'
import Nav from './components/nav'
// import ProductConTextPrivider
import ProductsContextPrivider from './components/productcontext'
import Foter from './components/foter'
import 'normalize.css'
import '../scss/index.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ProductsContextPrivider>
          {/* <Nav /> */}
          {children}
          <Foter />
        </ProductsContextPrivider>
      </body>
    </html>
  )
}
